### PR TITLE
Suggestion for improvement

### PR DESCRIPTION
**Pull request by xxalfa**
Troubleshooting an offset errors.

### CODE REVIEW

**Comment by MrGabriCavi** [comment]
Thanks xxalfa

**Comment by xxalfa** [comment]
The changes made by me are too massive, so I recommend not merge.

**Comment by jbdemonte** [comment]
Sorry, I missed your contribution (over-booked for a while...)
If you want to talk about this by email, please contact me

**Comment by xxalfa** [comment]
For sure. Where about it, we want to talk about?

**Comment by xxalfa** [comment]
I had previously written to you already via email. xxalfa@gmail.com

**Pull request closed without merging**
